Adding WNC sentence type
AeroRust/nmea pull request #110
Opened 2023-11-08 18:26 UTC by jarrod817

2023-11-08 18:27 UTC, jarrod817 commented
I would like to propose adding the WNC sentence type.

2023-11-21 14:22 UTC, elpiel commented on src/sentences/wnc.rs
> +/// - $GPWNC,12.3,N,45.6,K,DEST,START*hh
Would you mind adding docs about the fields and also a link to https://gpsd.gitlab.io/gpsd/NMEA.html#_wnc_distance_waypoint_to_waypoint ?

E.g.:

https://github.com/AeroRust/nmea/blob/db5c7d80e2b5766463b04b7855e809a520325a16/src/sentences/rmz.rs#L20-L35

2023-11-21 14:24 UTC, elpiel approved these changes
Only a minor thing regarding the docs and I don't have any feedback on the actual implementation.

Once again thank you for you contribution!

2023-11-22 01:27 UTC, jarrod817 reviewed
Added documentation

2023-11-23 09:00 UTC, elpiel requested changes
Ok, so I took a look again this morning and I also remembered a few things.
Please add these things to the PR:
- [ ] A feature for the sentence to be enabled in Cargo.toml (enabled for `waypoint` feature too)
- [ ] add the example sentence in `all_supported_messages.rs` test

I've also suggested changes to the docs to resemble other places. I do wish to make the docs consistent across the crate eventually.

2023-11-23 09:00 UTC, elpiel commented on src/sentences/wnc.rs
> +///
```suggestion
/// ```text
///             1  2  3  4   5    6  
///             |  |  |  |   |    |  
///     $--WNC,x.x,N,x.x,K,c--c,c--c*hh
/// ```
```

2023-11-23 09:00 UTC, elpiel commented on src/sentences/wnc.rs
> +/// - $GPWNC,200.00,N,370.40,K,Dest,Origin*58
```suggestion
/// WNC - Distance - Waypoint to Waypoint
/// 
/// <https://gpsd.gitlab.io/gpsd/NMEA.html#_wnc_distance_waypoint_to_waypoint>
///
/// Examples of WNC sentences:
/// - $GPWNC,200.00,N,370.40,K,Dest,Origin*58
```

2023-11-23 09:06 UTC, elpiel commented on src/sentences/wnc.rs
> +};
also a good way to organize imports is to have:

1. std/core
2. external crate
3. crate and super imports

https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#stdexternalcrate

No need to change it though, just letting you know.

2023-11-23 09:10 UTC, elpiel commented
I've also fixed the MSRV and all the warnings so you should be good to go if your code follows rustfmt/clippy.

2023-12-20 17:04 UTC, elpiel commented on src/parse.rs
> +                        parse_zda(nmea_sentence).map(ParseResult::WNC)
```suggestion
                        parse_wnc(nmea_sentence).map(ParseResult::WNC)
```

2023-12-21 06:32 UTC, elpiel approved these changes

2023-12-21 06:52 UTC, merged