Initialize APA
AeroRust/nmea pull request #119
Opened 2024-02-09 05:13 UTC by ANG13T

2024-02-12 06:54 UTC, elpiel requested changes
In general, pretty good PR! Thank you for your contribution.
There are a few minor things I found and the use of enums over bool/char would be ideal.

We should make a good examples with one of the other sentences to follow when developing a new one. Not all impls are in sync let alone the documentation so we should have a better guidance and an example to follow

2024-02-12 06:54 UTC, elpiel commented on src/sentences/apa.rs
> +// Example: $GPAPA,A,A,0.10,R,N,V,V,011,M,DEST,011,M*82
```suggestion
/// Example: `$GPAPA,A,A,0.10,R,N,V,V,011,M,DEST,011,M*82`
```

2024-02-12 06:54 UTC, elpiel commented on src/sentences/apa.rs
> +//
```suggestion
/// Field Number:
///
/// 1. Status, BOOLEAN, V = Loran-C Blink or SNR warning A = general warning flag or other navigation systems when a reliable fix is not available
/// 2. Status, BOOLEAN, V = Loran-C Cycle Lock warning flag A = OK or not used
/// 3. Cross Track Error Magnitude
/// 4. Status, BOOLEAN, L = Left or R = Right
/// 5. Cross Track Units, N = Nautical miles or K = Kilometers
/// 6. Status, BOOLEAN, A = Arrival Circle Entered, V = Not Entered
/// 7. Status, BOOLEAN, A = Perpendicular passed at waypoint, V = Not Passed
/// 8. Bearing origin to destination
/// 9. M = Magnetic, T = True
/// 10. Destination Waypoint ID
/// 11. Checksum
///
```

2024-02-12 06:54 UTC, elpiel commented on src/sentences/apa.rs
> +///
```suggestion
/// ```
///
```

2024-02-12 06:54 UTC, elpiel commented on Cargo.toml
> +APA = []
- [ ] Can you, please, move it down to be alphabetically ordered

2024-02-12 06:54 UTC, elpiel commented on src/sentences/aam.rs
> -///   4. Units of radiuos, nautical miles
Good catch!

2024-02-12 06:54 UTC, elpiel commented on src/sentences/apa.rs
> +/// M is the waypoint name
```suggestion
/// Where the last "M" is the waypoint name
```

2024-02-12 06:54 UTC, elpiel commented on src/sentences/apa.rs
> +// 4. Status, BOOLEAN, L = Left or R = Right
I believe we should use enum instead of boolean, as boolean is a bit insufficient.

```suggestion
// 4. Direction to steer, L = Left or R = Right
```

2024-02-12 06:54 UTC, elpiel commented on src/sentences/apa.rs
> +// 9. M = Magnetic, T = True
Same goes for Magnetic/True. Seems a better fit for an enum instead.

2024-02-13 15:05 UTC, elpiel commented
- [ ] Now that #92 is merged, could you please add the `cfg_attr` for `defmt-03` on the APA struct? Thank you in advance!

2024-04-02 04:48 UTC, ANG13T commented
@elpiel Updated this PR with the fixes and suggestions! Let me know what you think. Thanks so much!

2024-05-05 07:42 UTC, closed without merging